name: trad
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  collection: ^1.19.1

dev_dependencies:
  build: ^2.4.2
  build_runner: ^2.4.15
  lint: ^2.7.0
  source_gen: ^2.0.0
  test: ^1.26.0
