name: trad
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
