// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'parser.dart';

// **************************************************************************
// Generator: ProductionBuilder
// **************************************************************************

const _$productions = [
  (Nonterminal('start'), 1),
  (Nonterminal('definitions'), 2),
  (Nonterminal('definitions'), 0),
  (Nonterminal('definition'), 1),
  (Nonterminal('definition'), 1),
  (Nonterminal('variableDeclaration'), 3),
  (Nonterminal('variableDeclaration'), 5),
  (Nonterminal('functionDeclaration'), 6),
  (Nonterminal('parameterList'), 1),
  (Nonterminal('parameterList'), 0),
  (Nonterminal('parameters'), 3),
  (Nonterminal('parameters'), 1),
  (Nonterminal('parameter'), 2),
  (Nonterminal('functionBody'), 1),
  (Nonterminal('functionBody'), 3),
  (Nonterminal('type'), 1),
  (Nonterminal('type'), 1),
  (Nonterminal('type'), 1),
  (Nonterminal('type'), 4),
  (Nonterminal('type'), 1),
  (Nonterminal('block'), 3),
  (Nonterminal('statements'), 2),
  (Nonterminal('statements'), 0),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('statement'), 1),
  (Nonterminal('expressionStatement'), 2),
  (Nonterminal('returnStatement'), 3),
  (Nonterminal('returnStatement'), 2),
  (Nonterminal('ifStatement'), 6),
  (Nonterminal('elseStatement'), 2),
  (Nonterminal('elseStatement'), 2),
  (Nonterminal('elseStatement'), 0),
  (Nonterminal('forStatement'), 8),
  (Nonterminal('whileStatement'), 5),
  (Nonterminal('breakStatement'), 2),
  (Nonterminal('breakStatement'), 2),
  (Nonterminal('expression'), 1),
  (Nonterminal('expression'), 1),
  (Nonterminal('assignmentExpression'), 3),
  (Nonterminal('conditionalExpression'), 5),
  (Nonterminal('conditionalExpression'), 1),
  (Nonterminal('logicalOrExpression'), 3),
  (Nonterminal('logicalOrExpression'), 1),
  (Nonterminal('logicalAndExpression'), 3),
  (Nonterminal('logicalAndExpression'), 1),
  (Nonterminal('equalityExpression'), 3),
  (Nonterminal('equalityExpression'), 3),
  (Nonterminal('equalityExpression'), 1),
  (Nonterminal('relationalExpression'), 3),
  (Nonterminal('relationalExpression'), 3),
  (Nonterminal('relationalExpression'), 3),
  (Nonterminal('relationalExpression'), 3),
  (Nonterminal('relationalExpression'), 1),
  (Nonterminal('additiveExpression'), 3),
  (Nonterminal('additiveExpression'), 3),
  (Nonterminal('additiveExpression'), 1),
  (Nonterminal('multiplicativeExpression'), 3),
  (Nonterminal('multiplicativeExpression'), 3),
  (Nonterminal('multiplicativeExpression'), 3),
  (Nonterminal('multiplicativeExpression'), 1),
  (Nonterminal('unaryExpression'), 2),
  (Nonterminal('unaryExpression'), 2),
  (Nonterminal('unaryExpression'), 1),
  (Nonterminal('primary'), 1),
  (Nonterminal('primary'), 1),
  (Nonterminal('primary'), 3),
  (Nonterminal('primary'), 1),
  (Nonterminal('literal'), 1),
  (Nonterminal('literal'), 1),
  (Nonterminal('literal'), 1),
  (Nonterminal('literal'), 1),
  (Nonterminal('literal'), 1),
  (Nonterminal('listLiteral'), 2),
  (Nonterminal('listLiteral'), 3),
  (Nonterminal('expressionList'), 3),
  (Nonterminal('expressionList'), 1),
  (Nonterminal('functionInvocation'), 2),
  (Nonterminal('arguments'), 3),
  (Nonterminal('arguments'), 2),
];

// **************************************************************************
// Generator: ParsingTableBuilder
// **************************************************************************

const _$parsingTable = [
  {
    'definitions': Action.goto(1),
    '\$': Action.reduce(2),
    'int': Action.reduce(2),
    'String': Action.reduce(2),
    'bool': Action.reduce(2),
    'List': Action.reduce(2),
    'void': Action.reduce(2),
  },
  {
    'definition': Action.goto(2),
    'variableDeclaration': Action.goto(3),
    'functionDeclaration': Action.goto(4),
    'type': Action.goto(5),
    'int': Action.shift(6),
    'String': Action.shift(7),
    'bool': Action.shift(8),
    'List': Action.shift(9),
    'void': Action.shift(10),
    '\$': Action.accept,
  },
  {
    '\$': Action.reduce(1),
    'int': Action.reduce(1),
    'String': Action.reduce(1),
    'bool': Action.reduce(1),
    'List': Action.reduce(1),
    'void': Action.reduce(1),
  },
  {
    '\$': Action.reduce(3),
    'int': Action.reduce(3),
    'String': Action.reduce(3),
    'bool': Action.reduce(3),
    'List': Action.reduce(3),
    'void': Action.reduce(3),
  },
  {
    '\$': Action.reduce(4),
    'int': Action.reduce(4),
    'String': Action.reduce(4),
    'bool': Action.reduce(4),
    'List': Action.reduce(4),
    'void': Action.reduce(4),
  },
  {
    'id': Action.shift(11),
  },
  {
    'id': Action.reduce(15),
    '>': Action.reduce(15),
  },
  {
    'id': Action.reduce(16),
    '>': Action.reduce(16),
  },
  {
    'id': Action.reduce(17),
    '>': Action.reduce(17),
  },
  {
    '<': Action.shift(12),
  },
  {
    'id': Action.reduce(19),
    '>': Action.reduce(19),
  },
  {
    ';': Action.shift(13),
    '=': Action.shift(14),
    '(': Action.shift(15),
  },
  {
    'type': Action.goto(16),
    'int': Action.shift(6),
    'String': Action.shift(7),
    'bool': Action.shift(8),
    'List': Action.shift(9),
    'void': Action.shift(10),
  },
  {
    '\$': Action.reduce(5),
    'int': Action.reduce(5),
    'String': Action.reduce(5),
    'bool': Action.reduce(5),
    'List': Action.reduce(5),
    'void': Action.reduce(5),
    '}': Action.reduce(5),
    '{': Action.reduce(5),
    'return': Action.reduce(5),
    'if': Action.reduce(5),
    'for': Action.reduce(5),
    'while': Action.reduce(5),
    'break': Action.reduce(5),
    'continue': Action.reduce(5),
    'id': Action.reduce(5),
    '-': Action.reduce(5),
    '!': Action.reduce(5),
    '(': Action.reduce(5),
    'intLiteral': Action.reduce(5),
    'str': Action.reduce(5),
    'true': Action.reduce(5),
    'false': Action.reduce(5),
    '[': Action.reduce(5),
  },
  {
    'expression': Action.goto(17),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'parameterList': Action.goto(40),
    'parameters': Action.goto(41),
    'parameter': Action.goto(42),
    'type': Action.goto(43),
    'int': Action.shift(6),
    'String': Action.shift(7),
    'bool': Action.shift(8),
    'List': Action.shift(9),
    'void': Action.shift(10),
    ')': Action.reduce(9),
  },
  {
    '>': Action.shift(44),
  },
  {
    ';': Action.shift(45),
  },
  {
    ';': Action.reduce(42),
    ')': Action.reduce(42),
    ']': Action.reduce(42),
    ',': Action.reduce(42),
    ':': Action.reduce(42),
  },
  {
    ';': Action.reduce(43),
    ')': Action.reduce(43),
    ']': Action.reduce(43),
    ',': Action.reduce(43),
    ':': Action.reduce(43),
  },
  {
    '=': Action.shift(46),
    'arguments': Action.goto(47),
    '(': Action.shift(48),
    '<=': Action.reduce(70),
    '>=': Action.reduce(70),
    '<': Action.reduce(70),
    '>': Action.reduce(70),
    '==': Action.reduce(70),
    '!=': Action.reduce(70),
    '?': Action.reduce(70),
    ';': Action.reduce(70),
    '||': Action.reduce(70),
    '&&': Action.reduce(70),
    '+': Action.reduce(70),
    '-': Action.reduce(70),
    '*': Action.reduce(70),
    '~/': Action.reduce(70),
    '%': Action.reduce(70),
    ')': Action.reduce(70),
    ']': Action.reduce(70),
    ',': Action.reduce(70),
    ':': Action.reduce(70),
  },
  {
    '?': Action.shift(49),
    '||': Action.shift(50),
    ';': Action.reduce(46),
    ')': Action.reduce(46),
    ']': Action.reduce(46),
    ',': Action.reduce(46),
    ':': Action.reduce(46),
  },
  {
    '&&': Action.shift(51),
    '?': Action.reduce(48),
    ';': Action.reduce(48),
    '||': Action.reduce(48),
    ')': Action.reduce(48),
    ']': Action.reduce(48),
    ',': Action.reduce(48),
    ':': Action.reduce(48),
  },
  {
    '?': Action.reduce(50),
    ';': Action.reduce(50),
    '||': Action.reduce(50),
    '&&': Action.reduce(50),
    ')': Action.reduce(50),
    ']': Action.reduce(50),
    ',': Action.reduce(50),
    ':': Action.reduce(50),
  },
  {
    '==': Action.shift(52),
    '!=': Action.shift(53),
    '?': Action.reduce(53),
    ';': Action.reduce(53),
    '||': Action.reduce(53),
    '&&': Action.reduce(53),
    ')': Action.reduce(53),
    ']': Action.reduce(53),
    ',': Action.reduce(53),
    ':': Action.reduce(53),
  },
  {
    '<=': Action.shift(54),
    '>=': Action.shift(55),
    '<': Action.shift(56),
    '>': Action.shift(57),
    '+': Action.shift(58),
    '-': Action.shift(59),
    '==': Action.reduce(58),
    '!=': Action.reduce(58),
    '?': Action.reduce(58),
    ';': Action.reduce(58),
    '||': Action.reduce(58),
    '&&': Action.reduce(58),
    ')': Action.reduce(58),
    ']': Action.reduce(58),
    ',': Action.reduce(58),
    ':': Action.reduce(58),
  },
  {
    '*': Action.shift(60),
    '~/': Action.shift(61),
    '%': Action.shift(62),
    '<=': Action.reduce(61),
    '>=': Action.reduce(61),
    '<': Action.reduce(61),
    '>': Action.reduce(61),
    '==': Action.reduce(61),
    '!=': Action.reduce(61),
    '?': Action.reduce(61),
    ';': Action.reduce(61),
    '||': Action.reduce(61),
    '&&': Action.reduce(61),
    '+': Action.reduce(61),
    '-': Action.reduce(61),
    ')': Action.reduce(61),
    ']': Action.reduce(61),
    ',': Action.reduce(61),
    ':': Action.reduce(61),
  },
  {
    '<=': Action.reduce(65),
    '>=': Action.reduce(65),
    '<': Action.reduce(65),
    '>': Action.reduce(65),
    '==': Action.reduce(65),
    '!=': Action.reduce(65),
    '?': Action.reduce(65),
    ';': Action.reduce(65),
    '||': Action.reduce(65),
    '&&': Action.reduce(65),
    '+': Action.reduce(65),
    '-': Action.reduce(65),
    '*': Action.reduce(65),
    '~/': Action.reduce(65),
    '%': Action.reduce(65),
    ')': Action.reduce(65),
    ']': Action.reduce(65),
    ',': Action.reduce(65),
    ':': Action.reduce(65),
  },
  {
    'unaryExpression': Action.goto(63),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'unaryExpression': Action.goto(65),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '<=': Action.reduce(68),
    '>=': Action.reduce(68),
    '<': Action.reduce(68),
    '>': Action.reduce(68),
    '==': Action.reduce(68),
    '!=': Action.reduce(68),
    '?': Action.reduce(68),
    ';': Action.reduce(68),
    '||': Action.reduce(68),
    '&&': Action.reduce(68),
    '+': Action.reduce(68),
    '-': Action.reduce(68),
    '*': Action.reduce(68),
    '~/': Action.reduce(68),
    '%': Action.reduce(68),
    ')': Action.reduce(68),
    ']': Action.reduce(68),
    ',': Action.reduce(68),
    ':': Action.reduce(68),
  },
  {
    '<=': Action.reduce(69),
    '>=': Action.reduce(69),
    '<': Action.reduce(69),
    '>': Action.reduce(69),
    '==': Action.reduce(69),
    '!=': Action.reduce(69),
    '?': Action.reduce(69),
    ';': Action.reduce(69),
    '||': Action.reduce(69),
    '&&': Action.reduce(69),
    '+': Action.reduce(69),
    '-': Action.reduce(69),
    '*': Action.reduce(69),
    '~/': Action.reduce(69),
    '%': Action.reduce(69),
    ')': Action.reduce(69),
    ']': Action.reduce(69),
    ',': Action.reduce(69),
    ':': Action.reduce(69),
  },
  {
    'expression': Action.goto(66),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '<=': Action.reduce(72),
    '>=': Action.reduce(72),
    '<': Action.reduce(72),
    '>': Action.reduce(72),
    '==': Action.reduce(72),
    '!=': Action.reduce(72),
    '?': Action.reduce(72),
    ';': Action.reduce(72),
    '||': Action.reduce(72),
    '&&': Action.reduce(72),
    '+': Action.reduce(72),
    '-': Action.reduce(72),
    '*': Action.reduce(72),
    '~/': Action.reduce(72),
    '%': Action.reduce(72),
    ')': Action.reduce(72),
    ']': Action.reduce(72),
    ',': Action.reduce(72),
    ':': Action.reduce(72),
  },
  {
    '<=': Action.reduce(73),
    '>=': Action.reduce(73),
    '<': Action.reduce(73),
    '>': Action.reduce(73),
    '==': Action.reduce(73),
    '!=': Action.reduce(73),
    '?': Action.reduce(73),
    ';': Action.reduce(73),
    '||': Action.reduce(73),
    '&&': Action.reduce(73),
    '+': Action.reduce(73),
    '-': Action.reduce(73),
    '*': Action.reduce(73),
    '~/': Action.reduce(73),
    '%': Action.reduce(73),
    ')': Action.reduce(73),
    ']': Action.reduce(73),
    ',': Action.reduce(73),
    ':': Action.reduce(73),
  },
  {
    '<=': Action.reduce(74),
    '>=': Action.reduce(74),
    '<': Action.reduce(74),
    '>': Action.reduce(74),
    '==': Action.reduce(74),
    '!=': Action.reduce(74),
    '?': Action.reduce(74),
    ';': Action.reduce(74),
    '||': Action.reduce(74),
    '&&': Action.reduce(74),
    '+': Action.reduce(74),
    '-': Action.reduce(74),
    '*': Action.reduce(74),
    '~/': Action.reduce(74),
    '%': Action.reduce(74),
    ')': Action.reduce(74),
    ']': Action.reduce(74),
    ',': Action.reduce(74),
    ':': Action.reduce(74),
  },
  {
    '<=': Action.reduce(75),
    '>=': Action.reduce(75),
    '<': Action.reduce(75),
    '>': Action.reduce(75),
    '==': Action.reduce(75),
    '!=': Action.reduce(75),
    '?': Action.reduce(75),
    ';': Action.reduce(75),
    '||': Action.reduce(75),
    '&&': Action.reduce(75),
    '+': Action.reduce(75),
    '-': Action.reduce(75),
    '*': Action.reduce(75),
    '~/': Action.reduce(75),
    '%': Action.reduce(75),
    ')': Action.reduce(75),
    ']': Action.reduce(75),
    ',': Action.reduce(75),
    ':': Action.reduce(75),
  },
  {
    '<=': Action.reduce(76),
    '>=': Action.reduce(76),
    '<': Action.reduce(76),
    '>': Action.reduce(76),
    '==': Action.reduce(76),
    '!=': Action.reduce(76),
    '?': Action.reduce(76),
    ';': Action.reduce(76),
    '||': Action.reduce(76),
    '&&': Action.reduce(76),
    '+': Action.reduce(76),
    '-': Action.reduce(76),
    '*': Action.reduce(76),
    '~/': Action.reduce(76),
    '%': Action.reduce(76),
    ')': Action.reduce(76),
    ']': Action.reduce(76),
    ',': Action.reduce(76),
    ':': Action.reduce(76),
  },
  {
    '<=': Action.reduce(77),
    '>=': Action.reduce(77),
    '<': Action.reduce(77),
    '>': Action.reduce(77),
    '==': Action.reduce(77),
    '!=': Action.reduce(77),
    '?': Action.reduce(77),
    ';': Action.reduce(77),
    '||': Action.reduce(77),
    '&&': Action.reduce(77),
    '+': Action.reduce(77),
    '-': Action.reduce(77),
    '*': Action.reduce(77),
    '~/': Action.reduce(77),
    '%': Action.reduce(77),
    ')': Action.reduce(77),
    ']': Action.reduce(77),
    ',': Action.reduce(77),
    ':': Action.reduce(77),
  },
  {
    ']': Action.shift(67),
    'expressionList': Action.goto(68),
    'expression': Action.goto(69),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    ')': Action.shift(70),
  },
  {
    ',': Action.shift(71),
    ')': Action.reduce(8),
  },
  {
    ')': Action.reduce(11),
    ',': Action.reduce(11),
  },
  {
    'id': Action.shift(72),
  },
  {
    'id': Action.reduce(18),
    '>': Action.reduce(18),
  },
  {
    '\$': Action.reduce(6),
    'int': Action.reduce(6),
    'String': Action.reduce(6),
    'bool': Action.reduce(6),
    'List': Action.reduce(6),
    'void': Action.reduce(6),
    '}': Action.reduce(6),
    '{': Action.reduce(6),
    'return': Action.reduce(6),
    'if': Action.reduce(6),
    'for': Action.reduce(6),
    'while': Action.reduce(6),
    'break': Action.reduce(6),
    'continue': Action.reduce(6),
    'id': Action.reduce(6),
    '-': Action.reduce(6),
    '!': Action.reduce(6),
    '(': Action.reduce(6),
    'intLiteral': Action.reduce(6),
    'str': Action.reduce(6),
    'true': Action.reduce(6),
    'false': Action.reduce(6),
    '[': Action.reduce(6),
  },
  {
    'expression': Action.goto(73),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '<=': Action.reduce(82),
    '>=': Action.reduce(82),
    '<': Action.reduce(82),
    '>': Action.reduce(82),
    '==': Action.reduce(82),
    '!=': Action.reduce(82),
    '?': Action.reduce(82),
    ';': Action.reduce(82),
    '||': Action.reduce(82),
    '&&': Action.reduce(82),
    '+': Action.reduce(82),
    '-': Action.reduce(82),
    '*': Action.reduce(82),
    '~/': Action.reduce(82),
    '%': Action.reduce(82),
    ')': Action.reduce(82),
    ']': Action.reduce(82),
    ',': Action.reduce(82),
    ':': Action.reduce(82),
  },
  {
    'expressionList': Action.goto(74),
    ')': Action.shift(75),
    'expression': Action.goto(69),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'expression': Action.goto(76),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'logicalAndExpression': Action.goto(77),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'equalityExpression': Action.goto(78),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'relationalExpression': Action.goto(79),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'relationalExpression': Action.goto(80),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'additiveExpression': Action.goto(81),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'additiveExpression': Action.goto(82),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'additiveExpression': Action.goto(83),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'additiveExpression': Action.goto(84),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'multiplicativeExpression': Action.goto(85),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'multiplicativeExpression': Action.goto(86),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'unaryExpression': Action.goto(87),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'unaryExpression': Action.goto(88),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'unaryExpression': Action.goto(89),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    'id': Action.shift(64),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '<=': Action.reduce(66),
    '>=': Action.reduce(66),
    '<': Action.reduce(66),
    '>': Action.reduce(66),
    '==': Action.reduce(66),
    '!=': Action.reduce(66),
    '?': Action.reduce(66),
    ';': Action.reduce(66),
    '||': Action.reduce(66),
    '&&': Action.reduce(66),
    '+': Action.reduce(66),
    '-': Action.reduce(66),
    '*': Action.reduce(66),
    '~/': Action.reduce(66),
    '%': Action.reduce(66),
    ')': Action.reduce(66),
    ']': Action.reduce(66),
    ',': Action.reduce(66),
    ':': Action.reduce(66),
  },
  {
    'arguments': Action.goto(47),
    '(': Action.shift(48),
    '<=': Action.reduce(70),
    '>=': Action.reduce(70),
    '<': Action.reduce(70),
    '>': Action.reduce(70),
    '==': Action.reduce(70),
    '!=': Action.reduce(70),
    '?': Action.reduce(70),
    ';': Action.reduce(70),
    '||': Action.reduce(70),
    '&&': Action.reduce(70),
    '+': Action.reduce(70),
    '-': Action.reduce(70),
    '*': Action.reduce(70),
    '~/': Action.reduce(70),
    '%': Action.reduce(70),
    ')': Action.reduce(70),
    ']': Action.reduce(70),
    ',': Action.reduce(70),
    ':': Action.reduce(70),
  },
  {
    '<=': Action.reduce(67),
    '>=': Action.reduce(67),
    '<': Action.reduce(67),
    '>': Action.reduce(67),
    '==': Action.reduce(67),
    '!=': Action.reduce(67),
    '?': Action.reduce(67),
    ';': Action.reduce(67),
    '||': Action.reduce(67),
    '&&': Action.reduce(67),
    '+': Action.reduce(67),
    '-': Action.reduce(67),
    '*': Action.reduce(67),
    '~/': Action.reduce(67),
    '%': Action.reduce(67),
    ')': Action.reduce(67),
    ']': Action.reduce(67),
    ',': Action.reduce(67),
    ':': Action.reduce(67),
  },
  {
    ')': Action.shift(90),
  },
  {
    '<=': Action.reduce(78),
    '>=': Action.reduce(78),
    '<': Action.reduce(78),
    '>': Action.reduce(78),
    '==': Action.reduce(78),
    '!=': Action.reduce(78),
    '?': Action.reduce(78),
    ';': Action.reduce(78),
    '||': Action.reduce(78),
    '&&': Action.reduce(78),
    '+': Action.reduce(78),
    '-': Action.reduce(78),
    '*': Action.reduce(78),
    '~/': Action.reduce(78),
    '%': Action.reduce(78),
    ')': Action.reduce(78),
    ']': Action.reduce(78),
    ',': Action.reduce(78),
    ':': Action.reduce(78),
  },
  {
    ']': Action.shift(91),
    ',': Action.shift(92),
  },
  {
    ']': Action.reduce(81),
    ',': Action.reduce(81),
    ')': Action.reduce(81),
  },
  {
    'functionBody': Action.goto(93),
    'block': Action.goto(94),
    '=>': Action.shift(95),
    '{': Action.shift(96),
  },
  {
    'parameter': Action.goto(97),
    'type': Action.goto(43),
    'int': Action.shift(6),
    'String': Action.shift(7),
    'bool': Action.shift(8),
    'List': Action.shift(9),
    'void': Action.shift(10),
  },
  {
    ')': Action.reduce(12),
    ',': Action.reduce(12),
  },
  {
    ';': Action.reduce(44),
    ')': Action.reduce(44),
    ']': Action.reduce(44),
    ',': Action.reduce(44),
    ':': Action.reduce(44),
  },
  {
    ')': Action.shift(98),
    ',': Action.shift(92),
  },
  {
    '<=': Action.reduce(84),
    '>=': Action.reduce(84),
    '<': Action.reduce(84),
    '>': Action.reduce(84),
    '==': Action.reduce(84),
    '!=': Action.reduce(84),
    '?': Action.reduce(84),
    ';': Action.reduce(84),
    '||': Action.reduce(84),
    '&&': Action.reduce(84),
    '+': Action.reduce(84),
    '-': Action.reduce(84),
    '*': Action.reduce(84),
    '~/': Action.reduce(84),
    '%': Action.reduce(84),
    ')': Action.reduce(84),
    ']': Action.reduce(84),
    ',': Action.reduce(84),
    ':': Action.reduce(84),
  },
  {
    ':': Action.shift(99),
  },
  {
    '&&': Action.shift(51),
    '?': Action.reduce(47),
    ';': Action.reduce(47),
    '||': Action.reduce(47),
    ')': Action.reduce(47),
    ']': Action.reduce(47),
    ',': Action.reduce(47),
    ':': Action.reduce(47),
  },
  {
    '?': Action.reduce(49),
    ';': Action.reduce(49),
    '||': Action.reduce(49),
    '&&': Action.reduce(49),
    ')': Action.reduce(49),
    ']': Action.reduce(49),
    ',': Action.reduce(49),
    ':': Action.reduce(49),
  },
  {
    '?': Action.reduce(51),
    ';': Action.reduce(51),
    '||': Action.reduce(51),
    '&&': Action.reduce(51),
    ')': Action.reduce(51),
    ']': Action.reduce(51),
    ',': Action.reduce(51),
    ':': Action.reduce(51),
  },
  {
    '?': Action.reduce(52),
    ';': Action.reduce(52),
    '||': Action.reduce(52),
    '&&': Action.reduce(52),
    ')': Action.reduce(52),
    ']': Action.reduce(52),
    ',': Action.reduce(52),
    ':': Action.reduce(52),
  },
  {
    '+': Action.shift(58),
    '-': Action.shift(59),
    '==': Action.reduce(54),
    '!=': Action.reduce(54),
    '?': Action.reduce(54),
    ';': Action.reduce(54),
    '||': Action.reduce(54),
    '&&': Action.reduce(54),
    ')': Action.reduce(54),
    ']': Action.reduce(54),
    ',': Action.reduce(54),
    ':': Action.reduce(54),
  },
  {
    '+': Action.shift(58),
    '-': Action.shift(59),
    '==': Action.reduce(55),
    '!=': Action.reduce(55),
    '?': Action.reduce(55),
    ';': Action.reduce(55),
    '||': Action.reduce(55),
    '&&': Action.reduce(55),
    ')': Action.reduce(55),
    ']': Action.reduce(55),
    ',': Action.reduce(55),
    ':': Action.reduce(55),
  },
  {
    '+': Action.shift(58),
    '-': Action.shift(59),
    '==': Action.reduce(56),
    '!=': Action.reduce(56),
    '?': Action.reduce(56),
    ';': Action.reduce(56),
    '||': Action.reduce(56),
    '&&': Action.reduce(56),
    ')': Action.reduce(56),
    ']': Action.reduce(56),
    ',': Action.reduce(56),
    ':': Action.reduce(56),
  },
  {
    '+': Action.shift(58),
    '-': Action.shift(59),
    '==': Action.reduce(57),
    '!=': Action.reduce(57),
    '?': Action.reduce(57),
    ';': Action.reduce(57),
    '||': Action.reduce(57),
    '&&': Action.reduce(57),
    ')': Action.reduce(57),
    ']': Action.reduce(57),
    ',': Action.reduce(57),
    ':': Action.reduce(57),
  },
  {
    '*': Action.shift(60),
    '~/': Action.shift(61),
    '%': Action.shift(62),
    '<=': Action.reduce(59),
    '>=': Action.reduce(59),
    '<': Action.reduce(59),
    '>': Action.reduce(59),
    '==': Action.reduce(59),
    '!=': Action.reduce(59),
    '?': Action.reduce(59),
    ';': Action.reduce(59),
    '||': Action.reduce(59),
    '&&': Action.reduce(59),
    '+': Action.reduce(59),
    '-': Action.reduce(59),
    ')': Action.reduce(59),
    ']': Action.reduce(59),
    ',': Action.reduce(59),
    ':': Action.reduce(59),
  },
  {
    '*': Action.shift(60),
    '~/': Action.shift(61),
    '%': Action.shift(62),
    '<=': Action.reduce(60),
    '>=': Action.reduce(60),
    '<': Action.reduce(60),
    '>': Action.reduce(60),
    '==': Action.reduce(60),
    '!=': Action.reduce(60),
    '?': Action.reduce(60),
    ';': Action.reduce(60),
    '||': Action.reduce(60),
    '&&': Action.reduce(60),
    '+': Action.reduce(60),
    '-': Action.reduce(60),
    ')': Action.reduce(60),
    ']': Action.reduce(60),
    ',': Action.reduce(60),
    ':': Action.reduce(60),
  },
  {
    '<=': Action.reduce(62),
    '>=': Action.reduce(62),
    '<': Action.reduce(62),
    '>': Action.reduce(62),
    '==': Action.reduce(62),
    '!=': Action.reduce(62),
    '?': Action.reduce(62),
    ';': Action.reduce(62),
    '||': Action.reduce(62),
    '&&': Action.reduce(62),
    '+': Action.reduce(62),
    '-': Action.reduce(62),
    '*': Action.reduce(62),
    '~/': Action.reduce(62),
    '%': Action.reduce(62),
    ')': Action.reduce(62),
    ']': Action.reduce(62),
    ',': Action.reduce(62),
    ':': Action.reduce(62),
  },
  {
    '<=': Action.reduce(63),
    '>=': Action.reduce(63),
    '<': Action.reduce(63),
    '>': Action.reduce(63),
    '==': Action.reduce(63),
    '!=': Action.reduce(63),
    '?': Action.reduce(63),
    ';': Action.reduce(63),
    '||': Action.reduce(63),
    '&&': Action.reduce(63),
    '+': Action.reduce(63),
    '-': Action.reduce(63),
    '*': Action.reduce(63),
    '~/': Action.reduce(63),
    '%': Action.reduce(63),
    ')': Action.reduce(63),
    ']': Action.reduce(63),
    ',': Action.reduce(63),
    ':': Action.reduce(63),
  },
  {
    '<=': Action.reduce(64),
    '>=': Action.reduce(64),
    '<': Action.reduce(64),
    '>': Action.reduce(64),
    '==': Action.reduce(64),
    '!=': Action.reduce(64),
    '?': Action.reduce(64),
    ';': Action.reduce(64),
    '||': Action.reduce(64),
    '&&': Action.reduce(64),
    '+': Action.reduce(64),
    '-': Action.reduce(64),
    '*': Action.reduce(64),
    '~/': Action.reduce(64),
    '%': Action.reduce(64),
    ')': Action.reduce(64),
    ']': Action.reduce(64),
    ',': Action.reduce(64),
    ':': Action.reduce(64),
  },
  {
    '<=': Action.reduce(71),
    '>=': Action.reduce(71),
    '<': Action.reduce(71),
    '>': Action.reduce(71),
    '==': Action.reduce(71),
    '!=': Action.reduce(71),
    '?': Action.reduce(71),
    ';': Action.reduce(71),
    '||': Action.reduce(71),
    '&&': Action.reduce(71),
    '+': Action.reduce(71),
    '-': Action.reduce(71),
    '*': Action.reduce(71),
    '~/': Action.reduce(71),
    '%': Action.reduce(71),
    ')': Action.reduce(71),
    ']': Action.reduce(71),
    ',': Action.reduce(71),
    ':': Action.reduce(71),
  },
  {
    '<=': Action.reduce(79),
    '>=': Action.reduce(79),
    '<': Action.reduce(79),
    '>': Action.reduce(79),
    '==': Action.reduce(79),
    '!=': Action.reduce(79),
    '?': Action.reduce(79),
    ';': Action.reduce(79),
    '||': Action.reduce(79),
    '&&': Action.reduce(79),
    '+': Action.reduce(79),
    '-': Action.reduce(79),
    '*': Action.reduce(79),
    '~/': Action.reduce(79),
    '%': Action.reduce(79),
    ')': Action.reduce(79),
    ']': Action.reduce(79),
    ',': Action.reduce(79),
    ':': Action.reduce(79),
  },
  {
    'expression': Action.goto(100),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '\$': Action.reduce(7),
    'int': Action.reduce(7),
    'String': Action.reduce(7),
    'bool': Action.reduce(7),
    'List': Action.reduce(7),
    'void': Action.reduce(7),
  },
  {
    '\$': Action.reduce(13),
    'int': Action.reduce(13),
    'String': Action.reduce(13),
    'bool': Action.reduce(13),
    'List': Action.reduce(13),
    'void': Action.reduce(13),
  },
  {
    'expression': Action.goto(101),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'statements': Action.goto(102),
    '}': Action.reduce(22),
    '{': Action.reduce(22),
    'return': Action.reduce(22),
    'if': Action.reduce(22),
    'for': Action.reduce(22),
    'while': Action.reduce(22),
    'break': Action.reduce(22),
    'continue': Action.reduce(22),
    'int': Action.reduce(22),
    'String': Action.reduce(22),
    'bool': Action.reduce(22),
    'List': Action.reduce(22),
    'void': Action.reduce(22),
    'id': Action.reduce(22),
    '-': Action.reduce(22),
    '!': Action.reduce(22),
    '(': Action.reduce(22),
    'intLiteral': Action.reduce(22),
    'str': Action.reduce(22),
    'true': Action.reduce(22),
    'false': Action.reduce(22),
    '[': Action.reduce(22),
  },
  {
    ')': Action.reduce(10),
    ',': Action.reduce(10),
  },
  {
    '<=': Action.reduce(83),
    '>=': Action.reduce(83),
    '<': Action.reduce(83),
    '>': Action.reduce(83),
    '==': Action.reduce(83),
    '!=': Action.reduce(83),
    '?': Action.reduce(83),
    ';': Action.reduce(83),
    '||': Action.reduce(83),
    '&&': Action.reduce(83),
    '+': Action.reduce(83),
    '-': Action.reduce(83),
    '*': Action.reduce(83),
    '~/': Action.reduce(83),
    '%': Action.reduce(83),
    ')': Action.reduce(83),
    ']': Action.reduce(83),
    ',': Action.reduce(83),
    ':': Action.reduce(83),
  },
  {
    'expression': Action.goto(103),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    ']': Action.reduce(80),
    ',': Action.reduce(80),
    ')': Action.reduce(80),
  },
  {
    ';': Action.shift(104),
  },
  {
    '}': Action.shift(105),
    'statement': Action.goto(106),
    'block': Action.goto(107),
    'expressionStatement': Action.goto(108),
    'returnStatement': Action.goto(109),
    'ifStatement': Action.goto(110),
    'forStatement': Action.goto(111),
    'whileStatement': Action.goto(112),
    'breakStatement': Action.goto(113),
    'variableDeclaration': Action.goto(114),
    '{': Action.shift(96),
    'expression': Action.goto(115),
    'return': Action.shift(116),
    'if': Action.shift(117),
    'for': Action.shift(118),
    'while': Action.shift(119),
    'break': Action.shift(120),
    'continue': Action.shift(121),
    'type': Action.goto(122),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'int': Action.shift(6),
    'String': Action.shift(7),
    'bool': Action.shift(8),
    'List': Action.shift(9),
    'void': Action.shift(10),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    ';': Action.reduce(45),
    ')': Action.reduce(45),
    ']': Action.reduce(45),
    ',': Action.reduce(45),
    ':': Action.reduce(45),
  },
  {
    '\$': Action.reduce(14),
    'int': Action.reduce(14),
    'String': Action.reduce(14),
    'bool': Action.reduce(14),
    'List': Action.reduce(14),
    'void': Action.reduce(14),
  },
  {
    '\$': Action.reduce(20),
    'int': Action.reduce(20),
    'String': Action.reduce(20),
    'bool': Action.reduce(20),
    'List': Action.reduce(20),
    'void': Action.reduce(20),
    '}': Action.reduce(20),
    '{': Action.reduce(20),
    'return': Action.reduce(20),
    'if': Action.reduce(20),
    'for': Action.reduce(20),
    'while': Action.reduce(20),
    'break': Action.reduce(20),
    'continue': Action.reduce(20),
    'id': Action.reduce(20),
    '-': Action.reduce(20),
    '!': Action.reduce(20),
    '(': Action.reduce(20),
    'intLiteral': Action.reduce(20),
    'str': Action.reduce(20),
    'true': Action.reduce(20),
    'false': Action.reduce(20),
    '[': Action.reduce(20),
    'else': Action.reduce(20),
  },
  {
    '}': Action.reduce(21),
    '{': Action.reduce(21),
    'return': Action.reduce(21),
    'if': Action.reduce(21),
    'for': Action.reduce(21),
    'while': Action.reduce(21),
    'break': Action.reduce(21),
    'continue': Action.reduce(21),
    'int': Action.reduce(21),
    'String': Action.reduce(21),
    'bool': Action.reduce(21),
    'List': Action.reduce(21),
    'void': Action.reduce(21),
    'id': Action.reduce(21),
    '-': Action.reduce(21),
    '!': Action.reduce(21),
    '(': Action.reduce(21),
    'intLiteral': Action.reduce(21),
    'str': Action.reduce(21),
    'true': Action.reduce(21),
    'false': Action.reduce(21),
    '[': Action.reduce(21),
  },
  {
    '}': Action.reduce(23),
    '{': Action.reduce(23),
    'return': Action.reduce(23),
    'if': Action.reduce(23),
    'for': Action.reduce(23),
    'while': Action.reduce(23),
    'break': Action.reduce(23),
    'continue': Action.reduce(23),
    'int': Action.reduce(23),
    'String': Action.reduce(23),
    'bool': Action.reduce(23),
    'List': Action.reduce(23),
    'void': Action.reduce(23),
    'id': Action.reduce(23),
    '-': Action.reduce(23),
    '!': Action.reduce(23),
    '(': Action.reduce(23),
    'intLiteral': Action.reduce(23),
    'str': Action.reduce(23),
    'true': Action.reduce(23),
    'false': Action.reduce(23),
    '[': Action.reduce(23),
  },
  {
    '}': Action.reduce(24),
    '{': Action.reduce(24),
    'return': Action.reduce(24),
    'if': Action.reduce(24),
    'for': Action.reduce(24),
    'while': Action.reduce(24),
    'break': Action.reduce(24),
    'continue': Action.reduce(24),
    'int': Action.reduce(24),
    'String': Action.reduce(24),
    'bool': Action.reduce(24),
    'List': Action.reduce(24),
    'void': Action.reduce(24),
    'id': Action.reduce(24),
    '-': Action.reduce(24),
    '!': Action.reduce(24),
    '(': Action.reduce(24),
    'intLiteral': Action.reduce(24),
    'str': Action.reduce(24),
    'true': Action.reduce(24),
    'false': Action.reduce(24),
    '[': Action.reduce(24),
  },
  {
    '}': Action.reduce(25),
    '{': Action.reduce(25),
    'return': Action.reduce(25),
    'if': Action.reduce(25),
    'for': Action.reduce(25),
    'while': Action.reduce(25),
    'break': Action.reduce(25),
    'continue': Action.reduce(25),
    'int': Action.reduce(25),
    'String': Action.reduce(25),
    'bool': Action.reduce(25),
    'List': Action.reduce(25),
    'void': Action.reduce(25),
    'id': Action.reduce(25),
    '-': Action.reduce(25),
    '!': Action.reduce(25),
    '(': Action.reduce(25),
    'intLiteral': Action.reduce(25),
    'str': Action.reduce(25),
    'true': Action.reduce(25),
    'false': Action.reduce(25),
    '[': Action.reduce(25),
  },
  {
    '}': Action.reduce(26),
    '{': Action.reduce(26),
    'return': Action.reduce(26),
    'if': Action.reduce(26),
    'for': Action.reduce(26),
    'while': Action.reduce(26),
    'break': Action.reduce(26),
    'continue': Action.reduce(26),
    'int': Action.reduce(26),
    'String': Action.reduce(26),
    'bool': Action.reduce(26),
    'List': Action.reduce(26),
    'void': Action.reduce(26),
    'id': Action.reduce(26),
    '-': Action.reduce(26),
    '!': Action.reduce(26),
    '(': Action.reduce(26),
    'intLiteral': Action.reduce(26),
    'str': Action.reduce(26),
    'true': Action.reduce(26),
    'false': Action.reduce(26),
    '[': Action.reduce(26),
  },
  {
    '}': Action.reduce(27),
    '{': Action.reduce(27),
    'return': Action.reduce(27),
    'if': Action.reduce(27),
    'for': Action.reduce(27),
    'while': Action.reduce(27),
    'break': Action.reduce(27),
    'continue': Action.reduce(27),
    'int': Action.reduce(27),
    'String': Action.reduce(27),
    'bool': Action.reduce(27),
    'List': Action.reduce(27),
    'void': Action.reduce(27),
    'id': Action.reduce(27),
    '-': Action.reduce(27),
    '!': Action.reduce(27),
    '(': Action.reduce(27),
    'intLiteral': Action.reduce(27),
    'str': Action.reduce(27),
    'true': Action.reduce(27),
    'false': Action.reduce(27),
    '[': Action.reduce(27),
  },
  {
    '}': Action.reduce(28),
    '{': Action.reduce(28),
    'return': Action.reduce(28),
    'if': Action.reduce(28),
    'for': Action.reduce(28),
    'while': Action.reduce(28),
    'break': Action.reduce(28),
    'continue': Action.reduce(28),
    'int': Action.reduce(28),
    'String': Action.reduce(28),
    'bool': Action.reduce(28),
    'List': Action.reduce(28),
    'void': Action.reduce(28),
    'id': Action.reduce(28),
    '-': Action.reduce(28),
    '!': Action.reduce(28),
    '(': Action.reduce(28),
    'intLiteral': Action.reduce(28),
    'str': Action.reduce(28),
    'true': Action.reduce(28),
    'false': Action.reduce(28),
    '[': Action.reduce(28),
  },
  {
    '}': Action.reduce(29),
    '{': Action.reduce(29),
    'return': Action.reduce(29),
    'if': Action.reduce(29),
    'for': Action.reduce(29),
    'while': Action.reduce(29),
    'break': Action.reduce(29),
    'continue': Action.reduce(29),
    'int': Action.reduce(29),
    'String': Action.reduce(29),
    'bool': Action.reduce(29),
    'List': Action.reduce(29),
    'void': Action.reduce(29),
    'id': Action.reduce(29),
    '-': Action.reduce(29),
    '!': Action.reduce(29),
    '(': Action.reduce(29),
    'intLiteral': Action.reduce(29),
    'str': Action.reduce(29),
    'true': Action.reduce(29),
    'false': Action.reduce(29),
    '[': Action.reduce(29),
  },
  {
    '}': Action.reduce(30),
    '{': Action.reduce(30),
    'return': Action.reduce(30),
    'if': Action.reduce(30),
    'for': Action.reduce(30),
    'while': Action.reduce(30),
    'break': Action.reduce(30),
    'continue': Action.reduce(30),
    'int': Action.reduce(30),
    'String': Action.reduce(30),
    'bool': Action.reduce(30),
    'List': Action.reduce(30),
    'void': Action.reduce(30),
    'id': Action.reduce(30),
    '-': Action.reduce(30),
    '!': Action.reduce(30),
    '(': Action.reduce(30),
    'intLiteral': Action.reduce(30),
    'str': Action.reduce(30),
    'true': Action.reduce(30),
    'false': Action.reduce(30),
    '[': Action.reduce(30),
  },
  {
    ';': Action.shift(123),
  },
  {
    'expression': Action.goto(124),
    ';': Action.shift(125),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '(': Action.shift(126),
  },
  {
    '(': Action.shift(127),
  },
  {
    '(': Action.shift(128),
  },
  {
    ';': Action.shift(129),
  },
  {
    ';': Action.shift(130),
  },
  {
    'id': Action.shift(131),
  },
  {
    '}': Action.reduce(31),
    '{': Action.reduce(31),
    'return': Action.reduce(31),
    'if': Action.reduce(31),
    'for': Action.reduce(31),
    'while': Action.reduce(31),
    'break': Action.reduce(31),
    'continue': Action.reduce(31),
    'int': Action.reduce(31),
    'String': Action.reduce(31),
    'bool': Action.reduce(31),
    'List': Action.reduce(31),
    'void': Action.reduce(31),
    'id': Action.reduce(31),
    '-': Action.reduce(31),
    '!': Action.reduce(31),
    '(': Action.reduce(31),
    'intLiteral': Action.reduce(31),
    'str': Action.reduce(31),
    'true': Action.reduce(31),
    'false': Action.reduce(31),
    '[': Action.reduce(31),
  },
  {
    ';': Action.shift(132),
  },
  {
    '}': Action.reduce(33),
    '{': Action.reduce(33),
    'return': Action.reduce(33),
    'if': Action.reduce(33),
    'for': Action.reduce(33),
    'while': Action.reduce(33),
    'break': Action.reduce(33),
    'continue': Action.reduce(33),
    'int': Action.reduce(33),
    'String': Action.reduce(33),
    'bool': Action.reduce(33),
    'List': Action.reduce(33),
    'void': Action.reduce(33),
    'id': Action.reduce(33),
    '-': Action.reduce(33),
    '!': Action.reduce(33),
    '(': Action.reduce(33),
    'intLiteral': Action.reduce(33),
    'str': Action.reduce(33),
    'true': Action.reduce(33),
    'false': Action.reduce(33),
    '[': Action.reduce(33),
  },
  {
    'expression': Action.goto(133),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    'variableDeclaration': Action.goto(134),
    'type': Action.goto(122),
    'int': Action.shift(6),
    'String': Action.shift(7),
    'bool': Action.shift(8),
    'List': Action.shift(9),
    'void': Action.shift(10),
  },
  {
    'expression': Action.goto(135),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '}': Action.reduce(40),
    '{': Action.reduce(40),
    'return': Action.reduce(40),
    'if': Action.reduce(40),
    'for': Action.reduce(40),
    'while': Action.reduce(40),
    'break': Action.reduce(40),
    'continue': Action.reduce(40),
    'int': Action.reduce(40),
    'String': Action.reduce(40),
    'bool': Action.reduce(40),
    'List': Action.reduce(40),
    'void': Action.reduce(40),
    'id': Action.reduce(40),
    '-': Action.reduce(40),
    '!': Action.reduce(40),
    '(': Action.reduce(40),
    'intLiteral': Action.reduce(40),
    'str': Action.reduce(40),
    'true': Action.reduce(40),
    'false': Action.reduce(40),
    '[': Action.reduce(40),
  },
  {
    '}': Action.reduce(41),
    '{': Action.reduce(41),
    'return': Action.reduce(41),
    'if': Action.reduce(41),
    'for': Action.reduce(41),
    'while': Action.reduce(41),
    'break': Action.reduce(41),
    'continue': Action.reduce(41),
    'int': Action.reduce(41),
    'String': Action.reduce(41),
    'bool': Action.reduce(41),
    'List': Action.reduce(41),
    'void': Action.reduce(41),
    'id': Action.reduce(41),
    '-': Action.reduce(41),
    '!': Action.reduce(41),
    '(': Action.reduce(41),
    'intLiteral': Action.reduce(41),
    'str': Action.reduce(41),
    'true': Action.reduce(41),
    'false': Action.reduce(41),
    '[': Action.reduce(41),
  },
  {
    ';': Action.shift(13),
    '=': Action.shift(14),
  },
  {
    '}': Action.reduce(32),
    '{': Action.reduce(32),
    'return': Action.reduce(32),
    'if': Action.reduce(32),
    'for': Action.reduce(32),
    'while': Action.reduce(32),
    'break': Action.reduce(32),
    'continue': Action.reduce(32),
    'int': Action.reduce(32),
    'String': Action.reduce(32),
    'bool': Action.reduce(32),
    'List': Action.reduce(32),
    'void': Action.reduce(32),
    'id': Action.reduce(32),
    '-': Action.reduce(32),
    '!': Action.reduce(32),
    '(': Action.reduce(32),
    'intLiteral': Action.reduce(32),
    'str': Action.reduce(32),
    'true': Action.reduce(32),
    'false': Action.reduce(32),
    '[': Action.reduce(32),
  },
  {
    ')': Action.shift(136),
  },
  {
    'expression': Action.goto(137),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    ')': Action.shift(138),
  },
  {
    'block': Action.goto(139),
    '{': Action.shift(96),
  },
  {
    ';': Action.shift(140),
  },
  {
    'block': Action.goto(141),
    '{': Action.shift(96),
  },
  {
    'elseStatement': Action.goto(142),
    'else': Action.shift(143),
    '}': Action.reduce(37),
    '{': Action.reduce(37),
    'return': Action.reduce(37),
    'if': Action.reduce(37),
    'for': Action.reduce(37),
    'while': Action.reduce(37),
    'break': Action.reduce(37),
    'continue': Action.reduce(37),
    'int': Action.reduce(37),
    'String': Action.reduce(37),
    'bool': Action.reduce(37),
    'List': Action.reduce(37),
    'void': Action.reduce(37),
    'id': Action.reduce(37),
    '-': Action.reduce(37),
    '!': Action.reduce(37),
    '(': Action.reduce(37),
    'intLiteral': Action.reduce(37),
    'str': Action.reduce(37),
    'true': Action.reduce(37),
    'false': Action.reduce(37),
    '[': Action.reduce(37),
  },
  {
    'expression': Action.goto(144),
    'assignmentExpression': Action.goto(18),
    'conditionalExpression': Action.goto(19),
    'id': Action.shift(20),
    'logicalOrExpression': Action.goto(21),
    'logicalAndExpression': Action.goto(22),
    'equalityExpression': Action.goto(23),
    'relationalExpression': Action.goto(24),
    'additiveExpression': Action.goto(25),
    'multiplicativeExpression': Action.goto(26),
    'unaryExpression': Action.goto(27),
    '-': Action.shift(28),
    '!': Action.shift(29),
    'primary': Action.goto(30),
    'literal': Action.goto(31),
    '(': Action.shift(32),
    'functionInvocation': Action.goto(33),
    'intLiteral': Action.shift(34),
    'str': Action.shift(35),
    'true': Action.shift(36),
    'false': Action.shift(37),
    'listLiteral': Action.goto(38),
    '[': Action.shift(39),
  },
  {
    '}': Action.reduce(39),
    '{': Action.reduce(39),
    'return': Action.reduce(39),
    'if': Action.reduce(39),
    'for': Action.reduce(39),
    'while': Action.reduce(39),
    'break': Action.reduce(39),
    'continue': Action.reduce(39),
    'int': Action.reduce(39),
    'String': Action.reduce(39),
    'bool': Action.reduce(39),
    'List': Action.reduce(39),
    'void': Action.reduce(39),
    'id': Action.reduce(39),
    '-': Action.reduce(39),
    '!': Action.reduce(39),
    '(': Action.reduce(39),
    'intLiteral': Action.reduce(39),
    'str': Action.reduce(39),
    'true': Action.reduce(39),
    'false': Action.reduce(39),
    '[': Action.reduce(39),
  },
  {
    '}': Action.reduce(34),
    '{': Action.reduce(34),
    'return': Action.reduce(34),
    'if': Action.reduce(34),
    'for': Action.reduce(34),
    'while': Action.reduce(34),
    'break': Action.reduce(34),
    'continue': Action.reduce(34),
    'int': Action.reduce(34),
    'String': Action.reduce(34),
    'bool': Action.reduce(34),
    'List': Action.reduce(34),
    'void': Action.reduce(34),
    'id': Action.reduce(34),
    '-': Action.reduce(34),
    '!': Action.reduce(34),
    '(': Action.reduce(34),
    'intLiteral': Action.reduce(34),
    'str': Action.reduce(34),
    'true': Action.reduce(34),
    'false': Action.reduce(34),
    '[': Action.reduce(34),
  },
  {
    'ifStatement': Action.goto(145),
    'block': Action.goto(146),
    'if': Action.shift(117),
    '{': Action.shift(96),
  },
  {
    ')': Action.shift(147),
  },
  {
    '}': Action.reduce(35),
    '{': Action.reduce(35),
    'return': Action.reduce(35),
    'if': Action.reduce(35),
    'for': Action.reduce(35),
    'while': Action.reduce(35),
    'break': Action.reduce(35),
    'continue': Action.reduce(35),
    'int': Action.reduce(35),
    'String': Action.reduce(35),
    'bool': Action.reduce(35),
    'List': Action.reduce(35),
    'void': Action.reduce(35),
    'id': Action.reduce(35),
    '-': Action.reduce(35),
    '!': Action.reduce(35),
    '(': Action.reduce(35),
    'intLiteral': Action.reduce(35),
    'str': Action.reduce(35),
    'true': Action.reduce(35),
    'false': Action.reduce(35),
    '[': Action.reduce(35),
  },
  {
    '}': Action.reduce(36),
    '{': Action.reduce(36),
    'return': Action.reduce(36),
    'if': Action.reduce(36),
    'for': Action.reduce(36),
    'while': Action.reduce(36),
    'break': Action.reduce(36),
    'continue': Action.reduce(36),
    'int': Action.reduce(36),
    'String': Action.reduce(36),
    'bool': Action.reduce(36),
    'List': Action.reduce(36),
    'void': Action.reduce(36),
    'id': Action.reduce(36),
    '-': Action.reduce(36),
    '!': Action.reduce(36),
    '(': Action.reduce(36),
    'intLiteral': Action.reduce(36),
    'str': Action.reduce(36),
    'true': Action.reduce(36),
    'false': Action.reduce(36),
    '[': Action.reduce(36),
  },
  {
    'block': Action.goto(148),
    '{': Action.shift(96),
  },
  {
    '}': Action.reduce(38),
    '{': Action.reduce(38),
    'return': Action.reduce(38),
    'if': Action.reduce(38),
    'for': Action.reduce(38),
    'while': Action.reduce(38),
    'break': Action.reduce(38),
    'continue': Action.reduce(38),
    'int': Action.reduce(38),
    'String': Action.reduce(38),
    'bool': Action.reduce(38),
    'List': Action.reduce(38),
    'void': Action.reduce(38),
    'id': Action.reduce(38),
    '-': Action.reduce(38),
    '!': Action.reduce(38),
    '(': Action.reduce(38),
    'intLiteral': Action.reduce(38),
    'str': Action.reduce(38),
    'true': Action.reduce(38),
    'false': Action.reduce(38),
    '[': Action.reduce(38),
  },
];
